# Generated by Django 4.2.6 on 2023-10-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0002_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name_plural': 'Tutorials'},
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
